### ISSUE TITLE
"Sorry x this is a christian channel" should be changed to "Sorry x this is an schristian minecraft server"

### ISSUE THREAD

**Issue by KyleWatsonDev** [Alcas1/SwearJar#3]
The default message for SwearJar for when someone swears is broken. It doesn't properly state what the schristian minecraft server is being violated. pls update or brobrobro.

**Comment by Alcas1** [comment]
#wontfix

**Comment by schristian** [comment]
This issue is happening for me too, thanks

**Comment by Alcas1** [comment]
Too bad
